[[blis]]
arch = "aarch64"
git-tree-sha1 = "05ac170be3d4485620281e1e8e5e02c486ebe58a"
os = "macos"

    [[blis.download]]
    sha256 = "63d96b620d6fcd4eb47d8040376ecea7476405c3ef11e2dac07b1ffc4ae9c132"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.8.1+3/blis.v0.8.1.aarch64-apple-darwin.tar.gz"
[[blis]]
arch = "aarch64"
git-tree-sha1 = "8f498e4bd1f59477bfb51f2d9b823a18b8013c79"
libc = "glibc"
os = "linux"

    [[blis.download]]
    sha256 = "29ba393c685edfd1118dcb2b025a06d6d36d66cfa4d5f7eee0f96e206855235a"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.8.1+3/blis.v0.8.1.aarch64-linux-gnu.tar.gz"
[[blis]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "803d3ea7deca7b2b22ff668fa98b8314872b9b08"
libc = "glibc"
os = "linux"

    [[blis.download]]
    sha256 = "a83ce7cf6aed389c4e2c0b3d908e617a2fa5990b9a8b1ac59693d6a2c1ced6ab"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.8.1+3/blis.v0.8.1.armv7l-linux-gnueabihf.tar.gz"
[[blis]]
arch = "x86_64"
git-tree-sha1 = "cc15acec1f5320a9559756c8186ce2df4313bbc6"
os = "macos"

    [[blis.download]]
    sha256 = "d603daad00a3a7132c278a3c7b168965de4e4b7513cca20cc69f94c85f24ea0a"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.8.1+3/blis.v0.8.1.x86_64-apple-darwin.tar.gz"
[[blis]]
arch = "x86_64"
git-tree-sha1 = "c678808668b42fcfc33cc9ee184e6dd4049378b0"
libc = "glibc"
os = "linux"

    [[blis.download]]
    sha256 = "25536e07f7f36f18481e1dc0114130d08a5b6193ab915f034b8038a47c7894c4"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.8.1+3/blis.v0.8.1.x86_64-linux-gnu.tar.gz"
[[blis]]
arch = "x86_64"
git-tree-sha1 = "9b10901309af1ce163df7492d064d7e0eb4a7e9a"
libc = "musl"
os = "linux"

    [[blis.download]]
    sha256 = "ae1278b8062c15f075f71095bcbf2b8867e19e996c33e838b10dac9a3fd0bba3"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.8.1+3/blis.v0.8.1.x86_64-linux-musl.tar.gz"
[[blis]]
arch = "x86_64"
git-tree-sha1 = "bb5c1065ff8f6e3fa76aebf21298000d58a7f79b"
os = "freebsd"

    [[blis.download]]
    sha256 = "718bcffb85d6600b3f0b1602bf96a0cf0af44400584448c2abd789d18d87a228"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.8.1+3/blis.v0.8.1.x86_64-unknown-freebsd.tar.gz"
[[blis]]
arch = "x86_64"
git-tree-sha1 = "2b18539f73f68db55d7c81dbbd38a18c270806e8"
os = "windows"

    [[blis.download]]
    sha256 = "cbb10bad9b42fa530cc185613a57b5e63d89490a935cfd8c0c60937bc699c0f6"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.8.1+3/blis.v0.8.1.x86_64-w64-mingw32.tar.gz"
