[[blis]]
arch = "aarch64"
git-tree-sha1 = "b907dca2397ad5eadebf520bb0445a8850f7d134"
os = "macos"

    [[blis.download]]
    sha256 = "6193d3fb3ecd7e3b941724d7e0a9afa939d4527cf00f328ca63023e872342eb9"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v2.0.0+2/blis.v2.0.0.aarch64-apple-darwin.tar.gz"
[[blis]]
arch = "aarch64"
git-tree-sha1 = "3b14511e48f8c2582da093a2ce53f1a768447d8c"
libc = "glibc"
os = "linux"

    [[blis.download]]
    sha256 = "58845e5542296fefd443f04850d113de50b9b94f9f59a37c072a0c71b5916a63"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v2.0.0+2/blis.v2.0.0.aarch64-linux-gnu.tar.gz"
[[blis]]
arch = "aarch64"
git-tree-sha1 = "01ea245a69b23f3668ea40222393c290a69f3b22"
libc = "musl"
os = "linux"

    [[blis.download]]
    sha256 = "aa425bccd18a4097f6c31941c2371df91c71580f12e85643e95e19720fbda847"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v2.0.0+2/blis.v2.0.0.aarch64-linux-musl.tar.gz"
[[blis]]
arch = "aarch64"
git-tree-sha1 = "6f8fe91c3d4da860dbcbe02fa3bdd0f83b662fe7"
os = "freebsd"

    [[blis.download]]
    sha256 = "0c0dd6a3527bffe331b30a60351f454c83612ea0a5bcc8381700186c8fb07ef2"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v2.0.0+2/blis.v2.0.0.aarch64-unknown-freebsd.tar.gz"
[[blis]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "adde2709a975315eba7a245aa819e1a9748f1b43"
libc = "glibc"
os = "linux"

    [[blis.download]]
    sha256 = "ff857cb4eca60e49859e562e945252d04d5c64b6cff1325811b006dc5d93952f"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v2.0.0+2/blis.v2.0.0.armv6l-linux-gnueabihf.tar.gz"
[[blis]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "da1b5a99378ace188fe16706e64a31155afd694c"
libc = "musl"
os = "linux"

    [[blis.download]]
    sha256 = "07bdf373ecdfc0aad3591be008e98f38e10de792c25dad51971b0a49c18ca1e1"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v2.0.0+2/blis.v2.0.0.armv6l-linux-musleabihf.tar.gz"
[[blis]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "adde2709a975315eba7a245aa819e1a9748f1b43"
libc = "glibc"
os = "linux"

    [[blis.download]]
    sha256 = "ff857cb4eca60e49859e562e945252d04d5c64b6cff1325811b006dc5d93952f"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v2.0.0+2/blis.v2.0.0.armv7l-linux-gnueabihf.tar.gz"
[[blis]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "da1b5a99378ace188fe16706e64a31155afd694c"
libc = "musl"
os = "linux"

    [[blis.download]]
    sha256 = "07bdf373ecdfc0aad3591be008e98f38e10de792c25dad51971b0a49c18ca1e1"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v2.0.0+2/blis.v2.0.0.armv7l-linux-musleabihf.tar.gz"
[[blis]]
arch = "i686"
git-tree-sha1 = "7613fbe37cef1b40e6da6bed48510e82f5c325cc"
libc = "glibc"
os = "linux"

    [[blis.download]]
    sha256 = "99beba070761ca043d9b3d7c0126a616ccd65f11d84a97975dee6e6a42eff676"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v2.0.0+2/blis.v2.0.0.i686-linux-gnu.tar.gz"
[[blis]]
arch = "i686"
git-tree-sha1 = "0c2283dc63ccd925cc059475300cae318c43bce7"
libc = "musl"
os = "linux"

    [[blis.download]]
    sha256 = "7464c9c5411d00a49e88cf280cbf9e265ef95a655a1b99a1e40eb7278425aec5"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v2.0.0+2/blis.v2.0.0.i686-linux-musl.tar.gz"
[[blis]]
arch = "i686"
git-tree-sha1 = "16d9b5d45b4d56e76c00a83e139d07478a9c1823"
os = "windows"

    [[blis.download]]
    sha256 = "98a17bc1d51c86dcf2ed5dc3df833dedc5d3e8f60fe5e92b05061be3e555deea"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v2.0.0+2/blis.v2.0.0.i686-w64-mingw32.tar.gz"
[[blis]]
arch = "powerpc64le"
git-tree-sha1 = "8b46790d93ed99f03b2129adb167b7d0185225a4"
libc = "glibc"
os = "linux"

    [[blis.download]]
    sha256 = "a91c758ca1843c27d90c825d3f565955a850425b87477ec2b91b0c1aabf29bc5"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v2.0.0+2/blis.v2.0.0.powerpc64le-linux-gnu.tar.gz"
[[blis]]
arch = "riscv64"
git-tree-sha1 = "99f8257805e36438548bd59eb0bef569fc14ffea"
libc = "glibc"
os = "linux"

    [[blis.download]]
    sha256 = "5b9722c5430dfd1a4514ffe186bf7a46b00c1ff7a94b0babd809f9bf4f92dafc"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v2.0.0+2/blis.v2.0.0.riscv64-linux-gnu.tar.gz"
[[blis]]
arch = "x86_64"
git-tree-sha1 = "fc7198d728b149cdebc3fa7c1d59a7808b65fc70"
os = "macos"

    [[blis.download]]
    sha256 = "8784b32118cb7a53ed76e3c2de448c6ba7031fb3fd421d7526d07df7e3fbac0a"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v2.0.0+2/blis.v2.0.0.x86_64-apple-darwin.tar.gz"
[[blis]]
arch = "x86_64"
git-tree-sha1 = "eacdd0e2c05e7af860974c4cb4ff4bc694c3c781"
libc = "glibc"
os = "linux"

    [[blis.download]]
    sha256 = "c144cdc14abd1c4a269256b3ca68723d9fca7639a63261c75520ff92a0e9650a"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v2.0.0+2/blis.v2.0.0.x86_64-linux-gnu.tar.gz"
[[blis]]
arch = "x86_64"
git-tree-sha1 = "839632da7c54c343eb68067bcc0f3eb18e2f3b24"
libc = "musl"
os = "linux"

    [[blis.download]]
    sha256 = "639384255644c44263e811f9b9a9b79b93ccdddad02a94c8972336e27557eee3"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v2.0.0+2/blis.v2.0.0.x86_64-linux-musl.tar.gz"
[[blis]]
arch = "x86_64"
git-tree-sha1 = "9eef702abec31451065ee2b823dec92b45ce300d"
os = "freebsd"

    [[blis.download]]
    sha256 = "8a496b6df865c3dafe6b5cf031cc616d7ce86ba4007ebdad855b8c1229df9e3a"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v2.0.0+2/blis.v2.0.0.x86_64-unknown-freebsd.tar.gz"
[[blis]]
arch = "x86_64"
git-tree-sha1 = "9a0abb5b15a4a1c7c30e6124f13daf9a6bcd6b7f"
os = "windows"

    [[blis.download]]
    sha256 = "6e39a61ba90c7a66f828b0595a1ee7ad92db8d76b4b208f848a1c3daccb91f5d"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v2.0.0+2/blis.v2.0.0.x86_64-w64-mingw32.tar.gz"
