[[blis]]
arch = "aarch64"
git-tree-sha1 = "b714d499b79135ebd803b42c762f206f45b3b53a"
libc = "glibc"
os = "linux"

    [[blis.download]]
    sha256 = "6c7e1cbf0a1721179f45e5fb9b01c5a181fef9d8f32b1f435003e636259f5e52"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.8.0+1/blis.v0.8.0.aarch64-linux-gnu.tar.gz"
[[blis]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f8322b74d6c45eb9f2e8e18d230d50bcfbda0d27"
libc = "glibc"
os = "linux"

    [[blis.download]]
    sha256 = "e1846c0b6bde91adcd00ab8a03658dd5767701e59d7939a0011552ef8b66c0d6"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.8.0+1/blis.v0.8.0.armv7l-linux-gnueabihf.tar.gz"
[[blis]]
arch = "x86_64"
git-tree-sha1 = "10a04b4b47c12b9e6d8b1c168816cbd5552e37e1"
os = "macos"

    [[blis.download]]
    sha256 = "47256df22557444bb6b25884d5857a346b76df51d2868f48c21b0c689945213b"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.8.0+1/blis.v0.8.0.x86_64-apple-darwin.tar.gz"
[[blis]]
arch = "x86_64"
git-tree-sha1 = "a6d5663fc7b7cbf2fb6ec97cb6feee47d68c57c5"
libc = "glibc"
os = "linux"

    [[blis.download]]
    sha256 = "9d76198c4ac893b65b27fdeea1f4c148746b700ff738a95893a367418c868f4d"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.8.0+1/blis.v0.8.0.x86_64-linux-gnu.tar.gz"
[[blis]]
arch = "x86_64"
git-tree-sha1 = "2048603e90b86a99e8b0b871937c04dfeb35b33c"
libc = "musl"
os = "linux"

    [[blis.download]]
    sha256 = "4aa4c9320144b4f3b19f7621ce9b71457ce12cca01ed8af73098ff13e58d6b3f"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.8.0+1/blis.v0.8.0.x86_64-linux-musl.tar.gz"
[[blis]]
arch = "x86_64"
git-tree-sha1 = "2c70bf958b864aa80ba1d456d173bb1bc0c16a54"
os = "freebsd"

    [[blis.download]]
    sha256 = "55faa1b964872f47f2673e9d1d89ccc4c64b58bf5790516c88eb77d5570a63d4"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.8.0+1/blis.v0.8.0.x86_64-unknown-freebsd.tar.gz"
[[blis]]
arch = "x86_64"
git-tree-sha1 = "286b39349a3d6a5f7c782e4e9b7d0f146e316b7e"
os = "windows"

    [[blis.download]]
    sha256 = "ca880cb0bb999b1a314c8d6ece71be5d2363598765b4547dc7d2e4ad47fba35a"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.8.0+1/blis.v0.8.0.x86_64-w64-mingw32.tar.gz"
