[[blis]]
arch = "aarch64"
git-tree-sha1 = "a196a96048319302974d0bc478bf3a85ee7bfe6a"
libc = "glibc"
os = "linux"

    [[blis.download]]
    sha256 = "ecfa654d04f676a6696aeebcdab4a29654eb8240fb95fbe3736f75de49fe3e5e"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.8.0+0/blis.v0.8.0.aarch64-linux-gnu.tar.gz"
[[blis]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "518a62db8319b952bdc794a72d53f11c0a8265b6"
libc = "glibc"
os = "linux"

    [[blis.download]]
    sha256 = "3ca1f89e3030d060b6ed4cf4dd5e598b7aecacb53d50beea6a884234167cf632"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.8.0+0/blis.v0.8.0.armv7l-linux-gnueabihf.tar.gz"
[[blis]]
arch = "x86_64"
git-tree-sha1 = "6a834d2078d420aa75f6026c34381a25cc25a0a3"
os = "macos"

    [[blis.download]]
    sha256 = "12bed0907121c13e6261be4c6615e597d635fc48a72a72f69685454c7ab03cb4"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.8.0+0/blis.v0.8.0.x86_64-apple-darwin.tar.gz"
[[blis]]
arch = "x86_64"
git-tree-sha1 = "afa3d0a7ab73061fff7415e723b20679402af48b"
libc = "glibc"
os = "linux"

    [[blis.download]]
    sha256 = "d8e8863bba93e040f772f84f0284e210f4788b2f8c57eb7c57f321f80c144723"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.8.0+0/blis.v0.8.0.x86_64-linux-gnu.tar.gz"
[[blis]]
arch = "x86_64"
git-tree-sha1 = "0e351602c4123378b9b922d0ac2ba5bc6a988f80"
libc = "musl"
os = "linux"

    [[blis.download]]
    sha256 = "263841d9d7cb0650eb547f277cff0baa88b92d5ecff82781b82670e662380684"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.8.0+0/blis.v0.8.0.x86_64-linux-musl.tar.gz"
[[blis]]
arch = "x86_64"
git-tree-sha1 = "d5e644a908bd58b83ce8e33f04e62e31fc217648"
os = "freebsd"

    [[blis.download]]
    sha256 = "cb0b8f308d0ad7ce00b83db2626ddd75899ec362f738d804b0f73cfc3c178032"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.8.0+0/blis.v0.8.0.x86_64-unknown-freebsd.tar.gz"
[[blis]]
arch = "x86_64"
git-tree-sha1 = "8cb20f358c549f5fd4f5222ab45d436569c94109"
os = "windows"

    [[blis.download]]
    sha256 = "c0cb508e103668f48be3569ed166f932a82be45195202d1f8a96e9ac82205bdd"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.8.0+0/blis.v0.8.0.x86_64-w64-mingw32.tar.gz"
