[[blis]]
arch = "aarch64"
git-tree-sha1 = "81d69d8e4dff05cf53b38dfb2a7824d24ab0b217"
os = "macos"

    [[blis.download]]
    sha256 = "f6cc5dc98f41e32a9ec1f0773f916bea554c185b679c9785e95bcb5939a8b3f0"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v1.0.0+0/blis.v1.0.0.aarch64-apple-darwin.tar.gz"
[[blis]]
arch = "aarch64"
git-tree-sha1 = "a7c6e3f6f345e6089276810a57da870d6407bbe5"
libc = "glibc"
os = "linux"

    [[blis.download]]
    sha256 = "b3b8480a588f33128db52a1f1151adc5e14a8875317075bbb694148c5688ea1c"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v1.0.0+0/blis.v1.0.0.aarch64-linux-gnu.tar.gz"
[[blis]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "eff500413cdeaba9f81fab9428df3f763997f5ab"
libc = "glibc"
os = "linux"

    [[blis.download]]
    sha256 = "1343db84122b2e545be3ef94afcbd606310fc52aa9e8d937ce59dd04c71b05de"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v1.0.0+0/blis.v1.0.0.armv7l-linux-gnueabihf.tar.gz"
[[blis]]
arch = "x86_64"
git-tree-sha1 = "e3f67ac3e3d64cc5c2d61619eb826bc28f3d0a62"
os = "macos"

    [[blis.download]]
    sha256 = "95eb61f7c674bc994a5aab3a8316aace07f2034f4ebb6ef1ad2bf842e2940e1a"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v1.0.0+0/blis.v1.0.0.x86_64-apple-darwin.tar.gz"
[[blis]]
arch = "x86_64"
git-tree-sha1 = "2f7df723ac36bbae45596665f3467337083e0522"
libc = "glibc"
os = "linux"

    [[blis.download]]
    sha256 = "3aece0b737419f6b1db1e2f91c7da2e0968792949d08c311fd4d37d56b69cc4c"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v1.0.0+0/blis.v1.0.0.x86_64-linux-gnu.tar.gz"
[[blis]]
arch = "x86_64"
git-tree-sha1 = "7667a229ed672e2992279caa2c05119be7ff3dae"
libc = "musl"
os = "linux"

    [[blis.download]]
    sha256 = "0fbccc498cff53dccd5cb46776933a972777739df89b9b864bd413c9c983ada4"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v1.0.0+0/blis.v1.0.0.x86_64-linux-musl.tar.gz"
[[blis]]
arch = "x86_64"
git-tree-sha1 = "8152886f69f7677f385f4cb91c685d448b51ba67"
os = "freebsd"

    [[blis.download]]
    sha256 = "6e550d29a0fbe2793da54823ef11064ed6eb87e51873195f43bf9887e628008b"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v1.0.0+0/blis.v1.0.0.x86_64-unknown-freebsd.tar.gz"
[[blis]]
arch = "x86_64"
git-tree-sha1 = "9b9fc411ec291c3a58b3853ecd815fc9beab13ee"
os = "windows"

    [[blis.download]]
    sha256 = "7ca07cd03715a07e60b276e191b5155e35328aa8863e17b4462813f6298dc1b9"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v1.0.0+0/blis.v1.0.0.x86_64-w64-mingw32.tar.gz"
