[[blis]]
arch = "aarch64"
git-tree-sha1 = "817617fd65e94d5885b45f2d8cbb015fb10b0195"
os = "macos"

    [[blis.download]]
    sha256 = "442f4aa6f90db04e4892437f8a120fe06a89748604e6664ee802117ccc1980df"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.9.0+0/blis.v0.9.0.aarch64-apple-darwin.tar.gz"
[[blis]]
arch = "aarch64"
git-tree-sha1 = "00386c2295a568993168cb6aaea6e0cf740d4f56"
libc = "glibc"
os = "linux"

    [[blis.download]]
    sha256 = "8fc1d57bae950e7a6918a5bacb91fb03e35060fc912197cbd2e980b4b78a02cb"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.9.0+0/blis.v0.9.0.aarch64-linux-gnu.tar.gz"
[[blis]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d1bee6265bc54beb9cf556ee75aa3da8a6d55976"
libc = "glibc"
os = "linux"

    [[blis.download]]
    sha256 = "24a8e2ea1f11b4948b6ed00d3500cc0cc63f4b6357fe62b87c7791e515b6ac1a"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.9.0+0/blis.v0.9.0.armv7l-linux-gnueabihf.tar.gz"
[[blis]]
arch = "x86_64"
git-tree-sha1 = "ac4bde1abbfb6d9e685a8264a7e00b48d6308a60"
os = "macos"

    [[blis.download]]
    sha256 = "4dd5502c1e3f00e5fc096f7d569c54389f211a8be542b7ee84e97e10d43d9cb5"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.9.0+0/blis.v0.9.0.x86_64-apple-darwin.tar.gz"
[[blis]]
arch = "x86_64"
git-tree-sha1 = "b548e034d149feec83ed78f22ab942fea1ac3d12"
libc = "glibc"
os = "linux"

    [[blis.download]]
    sha256 = "ba083cd2adde6b78c02c64a3a5478762950f12fe1600253792220adca6bc2313"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.9.0+0/blis.v0.9.0.x86_64-linux-gnu.tar.gz"
[[blis]]
arch = "x86_64"
git-tree-sha1 = "28fb9d65ad156c58a9b1348e33ba8f760d39154e"
libc = "musl"
os = "linux"

    [[blis.download]]
    sha256 = "cb3aff789200c03e41723f4f643f3bb5849b4645acc3bb59edc82f13b9c2eef1"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.9.0+0/blis.v0.9.0.x86_64-linux-musl.tar.gz"
[[blis]]
arch = "x86_64"
git-tree-sha1 = "a0e7fb5fad54c130e4dda45502e6b2b9b3ada833"
os = "freebsd"

    [[blis.download]]
    sha256 = "18670c3835e8d2ad955f9aa7fd16b7e88bb33fb861f71ff26e49e84d24159bd0"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.9.0+0/blis.v0.9.0.x86_64-unknown-freebsd.tar.gz"
[[blis]]
arch = "x86_64"
git-tree-sha1 = "fb687e5c40a2b3c863cae762da21d978196342e1"
os = "windows"

    [[blis.download]]
    sha256 = "67bb6787b0912742990c1360de8051330ceb507bac1591fa60d81b3664250222"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.9.0+0/blis.v0.9.0.x86_64-w64-mingw32.tar.gz"
