[[blis]]
arch = "aarch64"
git-tree-sha1 = "842ed81479a791708f5681bc17793c5356c2ac4c"
os = "macos"

    [[blis.download]]
    sha256 = "ad8bafc125927b9fcee81cb78958d26d1f383a9d6fc7f3dd32dcfd3adc0c8212"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.8.1+2/blis.v0.8.1.aarch64-apple-darwin.tar.gz"
[[blis]]
arch = "aarch64"
git-tree-sha1 = "6a3cc19a931a93f072a70970f918f05ffb4c935f"
libc = "glibc"
os = "linux"

    [[blis.download]]
    sha256 = "d442dcf2e1a8b59a75c86a48081b63d618948d49e2e01e7bc2545feb0fe266f8"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.8.1+2/blis.v0.8.1.aarch64-linux-gnu.tar.gz"
[[blis]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8c71cc75c56b258d6be50bd767edb42345c768bb"
libc = "glibc"
os = "linux"

    [[blis.download]]
    sha256 = "44e9dad8083ac9f17218f3a3ec1f243aa1eb2dfcdf643691909f0315631a0714"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.8.1+2/blis.v0.8.1.armv7l-linux-gnueabihf.tar.gz"
[[blis]]
arch = "x86_64"
git-tree-sha1 = "567e1b2234ebc730bc16e33871144bf9b561f1fa"
os = "macos"

    [[blis.download]]
    sha256 = "6ac9a49d3e4c3a5dead4a2edd71e95159d9de832a30b1b7d3f5074d4150129ea"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.8.1+2/blis.v0.8.1.x86_64-apple-darwin.tar.gz"
[[blis]]
arch = "x86_64"
git-tree-sha1 = "f2f9f5b1c7af69f9f1c44f2f54c7f099ea53788d"
libc = "glibc"
os = "linux"

    [[blis.download]]
    sha256 = "1418dda3c30acfd04729535108c1ab10125063e14669868593f8e642a3657e22"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.8.1+2/blis.v0.8.1.x86_64-linux-gnu.tar.gz"
[[blis]]
arch = "x86_64"
git-tree-sha1 = "71333e88ed6888410b830a6d5e5ee831aeee47a9"
libc = "musl"
os = "linux"

    [[blis.download]]
    sha256 = "7e1e825f2ef480803a56d197aa4398b9921cfd5c9885e8c7d1ea5b0b0b754053"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.8.1+2/blis.v0.8.1.x86_64-linux-musl.tar.gz"
[[blis]]
arch = "x86_64"
git-tree-sha1 = "b7d5bef949a209264dd63fdbf0a16c3cf31595d9"
os = "freebsd"

    [[blis.download]]
    sha256 = "de504058ff47575c5e640b590dc7bf83b2a1f56c1ccc9c93b5378d58279229ec"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.8.1+2/blis.v0.8.1.x86_64-unknown-freebsd.tar.gz"
[[blis]]
arch = "x86_64"
git-tree-sha1 = "638ba52c79065e102a8aee1ac579704fa927db5e"
os = "windows"

    [[blis.download]]
    sha256 = "1c0f26cb7fd65e0ff8a672da8d07c11d9b4955f01130cef88fcc8e354bb8ff2f"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.8.1+2/blis.v0.8.1.x86_64-w64-mingw32.tar.gz"
